env:
  browser: true
  es6: true
extends:
  - 'airbnb'
  - 'prettier'
  - 'prettier/react'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  "import/no-extraneous-dependencies": ["error", {"devDependencies": true}],
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
}
