default_stages: [commit, push]
repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        exclude: test.*
    -   id: bandit
        name: bandit
        entry: bandit
        language: python
        types: [python]
        exclude: test.*
    -   id: pylint
        name: pylint
        entry: pylint --rcfile=backend/.pylintrc
        language: python
        types: [python]
        exclude: test.*
    -   id: pytest
        name: pytest
        entry: pytest backend
        language: python
        always_run: true
        pass_filenames: false
