FROM python:3.8-alpine3.10

RUN apk add --no-cache --virtual .build-deps gcc libc-dev make \
    && pip install pipenv

WORKDIR /app

COPY backend/Pipfile Pipfile
COPY backend/Pipfile.lock Pipfile.lock

RUN pipenv install --dev

EXPOSE 80
