version: '3'
services:
  backend:
    container_name: backend-container
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    command: uvicorn main:app --host 0.0.0.0 --port 81 --reload
    volumes:
      - '../backend:/app'
    links:
      - database
    ports:
      - "81:81"
    depends_on:
      - database
    environment:
      - HOST=${HOST}
      - PORT=81
      - SUDOKUBR_SECRET_KEY=${SUDOKUBR_SECRET_KEY}
      - SUDOKUBR_DB_USERNAME=${SUDOKUBR_DB_USERNAME} 
      - SUDOKUBR_DB_PASSWORD=${SUDOKUBR_DB_PASSWORD}
  
  database:
    image: 'mongo'
    restart: always
    container_name: 'mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'

      
  frontend:
    container_name: frontend-container
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    command: npm start
    volumes:
      - '../frontend:/app'
      - '/app/node_modules'
    links:
      - database
    ports:
      - "82:82"
    environment:
      - HOST=${HOST}
      - PORT=82
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true



  proxy:
    container_name: proxy-container
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - ENV=development
      - PORT=80



